update focusmanager to the "new" one
SharezoneApp/sharezone-app pull request #347
Opened 2023-02-05 11:47 UTC by Th3Ph4nt0m

As described in #338, so far the legacy variant has been used for the Focus. I have updated this to the "new" method. All components have been tested accordingly and work in the iOS 16.1 simulator.

Closes #338

2023-02-05 11:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SharezoneApp/sharezone-app?pullRequest=347) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SharezoneApp/sharezone-app?pullRequest=347) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SharezoneApp/sharezone-app?pullRequest=347) it.</sub>

2023-02-05 12:01 UTC, nilsreichardt commented
⬇️ Generated builds by [Codemagic](https://codemagic.io/app/629c82ea463af7ff553fc7a5/build/63df974022feca33eebac518) for commit 8f49b2c51ab7e843cf9fb7fecc20d8b620bda81c ⬇️

_Note_: Only Sharezone team members are able to install the iOS app.

| iOS | Android |
|:-:|:-:|
| ![image](https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https%3A%2F%2Fapi.codemagic.io%2Fartifacts%2F7692a3d7-eabb-41f3-8b6f-840cf4a73632%2F24fd19e7-123b-485f-8ff9-40b3e28c2284%2Fsharezone.ipa) <br /> [Download link](https://api.codemagic.io/artifacts/7692a3d7-eabb-41f3-8b6f-840cf4a73632/24fd19e7-123b-485f-8ff9-40b3e28c2284/sharezone.ipa) | ![image](https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https%3A%2F%2Fapi.codemagic.io%2Fartifacts%2F56a4f59e-c2df-4e3d-8af5-eda5778f629f%2Fabf0e826-7865-4ea0-a3b2-e5cb32566ff9%2Fapp-dev-release.apk) <br /> [Download link](https://api.codemagic.io/artifacts/56a4f59e-c2df-4e3d-8af5-eda5778f629f/abf0e826-7865-4ea0-a3b2-e5cb32566ff9/app-dev-release.apk) |

<!-- Codemagic App Preview; jobId: default -->

2023-02-05 22:08 UTC, Jonas-Sander commented
Hey, looks good, thanks!:)

The web preview and integration tests seems to be failing because the actions can't access the secrets. I think this is because this is an external PR - it can't access secrets so they can't be leaked by a PR with modified actions code by an "attacker". I think there might be a way to fix this, I'd have to look into it in the few coming days. If its an easy fix then I would implement it before merging, if its more complex we might just skip the failing actions and merge anyways.

@nilsreichardt Do you want to do the review since you opened the ticket?

2023-02-08 22:08 UTC, Jonas-Sander commented
Okay, so there are ways to fix the actions issue mentioned above (https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ - using `pull_request` and `workflow_run`) but a proper fix will take some time to implement.  
So for this PR I would just ignore the failing actions, I'm gonna open an issue for external PRs for the future.

2023-02-09 20:31 UTC, Jonas-Sander commented
@Th3Ph4nt0m Hey, since @nilsreichardt didn't have time to review yet, I'm just gonna do it.
I tested it on Android, seems to work. Code looks good.

I see that there are still some places where `FocusScope.of` is still used:  
![grafik](https://user-images.githubusercontent.com/29028262/217929819-16b924d9-8c04-4839-bbcd-019eeb4725fb.png)

Can you fix these as well? I can't push on your fork so it would be much appreciated :)  
After that we can merge 🎉

2023-02-09 20:32 UTC, Jonas-Sander requested changes
See above

2023-02-11 11:21 UTC, Th3Ph4nt0m commented
> See above

Sure, just updated the PR ;)

2023-02-13 13:49 UTC, Jonas-Sander approved these changes

2023-02-13 16:57 UTC, merged

2023-02-13 16:58 UTC, Jonas-Sander commented
Nice, thanks! :)  

You're the first external contributor, congratulations 🎉♥️