Fix dark theme dialog colors.
SharezoneApp/sharezone-app pull request #569
Opened 2023-04-05 20:34 UTC by Jonas-Sander

By using `ColorScheme.fromSwatch().copyWith(...)` the `ColorScheme` was tailored to light-mode which caused some dialogs to be displayed in the wrong colors when using dark mode.
Specifying the `Brightness` inside `ColorScheme.fromSeed` fixed this issue.

Fixes #167 
Fixes #168

2023-04-05 20:56 UTC, nilsreichardt commented
This PR also fixes #384

2023-04-05 20:58 UTC, nilsreichardt reviewed
<img width="1552" alt="Screenshot 2023-04-05 at 22 57 51" src="https://user-images.githubusercontent.com/24459435/230209974-b64c9747-f7a8-40e1-a102-6cf91b91ae12.png">

Snackbar in dark mode is not readable

2023-04-05 21:03 UTC, nilsreichardt commented
<img width="854" alt="image" src="https://user-images.githubusercontent.com/24459435/230210821-61d02c71-edf0-4589-9aed-e60acfce924c.png">

Wrong in the PR description (you need to swap the images)

2023-04-06 07:35 UTC, nilsreichardt requested changes
LGTM

The only thing that I have seen was that the snackbar text has the wrong color in dark mode

2023-04-09 21:36 UTC, Jonas-Sander commented on app/lib/widgets/apple_sign_in_button.dart
> +                    color: Colors.white,
As you can see in your last screen shot the icon was not completely white. I didn't find see this for the other icons in the app though.

2023-04-09 23:48 UTC, nilsreichardt approved these changes
LGTM

2023-04-10 00:38 UTC, merged